export const FETCH_ARTISTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';

export const FETCH_ALBUMS_SUCCESS = 'FETCH_ALBUMS_SUCCESS';

export const FETCH_TRACKS_SUCCESS = 'FETCH_TRACKS_SUCCESS';
export const ADD_TRACK_TO_HISTORY = 'ADD_TRACK_TO_HISTORY';

export const FETCH_TRACKHISTORY_SUCCESS = 'FETCH_TRACKHISTORY_SUCCESS';

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
